name: mi_tension
description: "TFG para DAM."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.5
  http: ^1.2.1
  pinput: ^6.0.2
  intl: ^0.20.2
  fl_chart: ^1.2.0
  flutter_local_notifications: 18.0.1
  timezone: 0.9.4
  flutter_timezone: 5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/AtomoLogoPrincipal.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/verificarCodigo/
    - assets/images/home/
    - assets/images/pressureAnalysis/
  fonts:
    - family: sf
      fonts:
        - asset: assets/fonts/sf-pro-rounded.ttf